version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    restart: unless-stopped
